import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { initInputComponents, mountDatePicker, mountTimePicker, mountSearch } from '../src/components-input.js';
function fixture(t, markup = '<div id="host"></div>') { const dom = new JSDOM(`<!doctype html><body>${markup}`, { url: 'https://quiet.test' }); const { window } = dom; window.matchMedia = () => ({ matches: true }); t.after(() => window.close()); return { window, doc: window.document, host: window.document.querySelector('#host') }; }
function key(window, el, key, extra = {}) { const event = new window.KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, ...extra }); el.dispatchEvent(event); return event; }
function button(host, text) { return [...host.querySelectorAll('button')].find(node => node.textContent === text); }
function type(window, input, value) { input.value = value; input.dispatchEvent(new window.Event('input', { bubbles: true })); }

test('menu skips disabled items, wraps roving focus, typeahead selects and Escape restores invoker', t => {
  const { doc, window } = fixture(t, '<button id="trigger" data-qm-menu-trigger="menu">Menu</button><div id="menu" role="menu" hidden><button role="menuitem">Alpha</button><button role="menuitem" disabled>Beta</button><button role="menuitem">Gamma</button></div>');
  const cleanup = initInputComponents(doc); t.after(cleanup); const trigger = doc.querySelector('#trigger'); trigger.click(); assert.equal(doc.activeElement.textContent, 'Alpha'); key(window, doc.activeElement, 'ArrowUp'); assert.equal(doc.activeElement.textContent, 'Gamma'); key(window, doc.activeElement, 'Home'); assert.equal(doc.activeElement.textContent, 'Alpha'); key(window, doc.activeElement, 'g'); assert.equal(doc.activeElement.textContent, 'Gamma'); key(window, doc.activeElement, 'Escape'); assert.equal(doc.activeElement, trigger); assert.equal(doc.querySelector('#menu').hidden, true); assert.equal(trigger.getAttribute('aria-expanded'), 'false');
});
test('menu checkbox emits checked state and radio selection is mutually exclusive', t => {
  const { doc } = fixture(t, '<button id="trigger" data-qm-menu-trigger="menu">Menu</button><div id="menu" role="menu" hidden><button role="menuitemcheckbox" aria-checked="false" data-value="sync">Sync</button><div role="group"><button role="menuitemradio" aria-checked="true">One</button><button role="menuitemradio" aria-checked="false">Two</button></div></div>'); const cleanup = initInputComponents(doc); t.after(cleanup); let selected; doc.addEventListener('qm:menu-select', event => selected = event.detail); doc.querySelector('#trigger').click(); doc.querySelector('[role="menuitemcheckbox"]').click(); assert.equal(selected.checked, true); assert.equal(selected.value, 'sync'); doc.querySelector('#trigger').click(); const radios = doc.querySelectorAll('[role="menuitemradio"]'); radios[1].click(); assert.equal(radios[0].getAttribute('aria-checked'), 'false'); assert.equal(radios[1].getAttribute('aria-checked'), 'true');
});
test('dropdown filters safely, keeps input focus and commits option values with keyboard', t => {
  const { doc, window } = fixture(t, '<div data-qm-combobox><label for="choice">Choice</label><input id="choice" role="combobox"><div role="listbox" hidden><div role="option" data-value="android">Android</div><div role="option" data-value="ios">iOS</div><div role="option" aria-disabled="true">Other</div></div></div>'); const cleanup = initInputComponents(doc); t.after(cleanup); const input = doc.querySelector('input'); let change; doc.addEventListener('qm:combobox-change', event => change = event.detail); input.focus(); type(window, input, 'iO'); assert.equal(doc.querySelector('[data-value="android"]').hidden, true); assert.ok(input.getAttribute('aria-activedescendant')); key(window, input, 'Enter'); assert.equal(input.value, 'iOS'); assert.equal(change.value, 'ios'); assert.equal(doc.activeElement, input); assert.equal(input.getAttribute('aria-expanded'), 'false');
});
test('date picker traverses leap day and month/year boundaries without timezone shifts', t => {
  const { doc, window, host } = fixture(t); const picker = mountDatePicker(host, { value: '2024-02-28', min: '2024-01-01', max: '2025-12-31' }); t.after(() => picker.destroy()); const day = host.querySelector('[data-date="2024-02-28"]'); day.focus(); key(window, day, 'ArrowRight'); assert.equal(doc.activeElement.dataset.date, '2024-02-29'); key(window, doc.activeElement, 'ArrowRight'); assert.equal(doc.activeElement.dataset.date, '2024-03-01'); key(window, doc.activeElement, 'PageUp', { shiftKey: true }); assert.equal(doc.activeElement.dataset.date, '2024-01-01'); picker.setValue('2024-12-31'); host.querySelector('[tabindex="0"]').focus(); key(window, doc.activeElement, 'ArrowRight'); assert.equal(doc.activeElement.dataset.date, '2025-01-01'); assert.throws(() => picker.setValue('2023-02-29'), RangeError);
});
test('date draft/cancel/commit and bounds are separate, range reversal creates ordered endpoints', t => {
  const { host } = fixture(t); let selected; const picker = mountDatePicker(host, { range: true, value: { start: '2026-09-10', end: '2026-09-12' }, min: '2026-09-01', max: '2026-09-30', onChange: value => selected = value }); t.after(() => picker.destroy()); assert.equal(host.querySelector('[data-date="2026-08-31"]').disabled, true); host.querySelector('[data-date="2026-09-20"]').click(); host.querySelector('[data-date="2026-09-18"]').click(); assert.deepEqual(picker.value, { start: '2026-09-10', end: '2026-09-12' }); button(host, 'Cancel').click(); assert.equal(host.querySelector('[data-date="2026-09-10"]').getAttribute('aria-selected'), 'true'); host.querySelector('[data-date="2026-09-20"]').click(); host.querySelector('[data-date="2026-09-18"]').click(); button(host, 'OK').click(); assert.deepEqual(selected, { start: '2026-09-18', end: '2026-09-20' });
});
test('date input rejects invalid leap days and reversed ranges before commit', t => {
  const { window, host } = fixture(t); const picker = mountDatePicker(host, { range: true, value: { start: '2024-02-01', end: '2024-02-02' } }); t.after(() => picker.destroy()); button(host, 'Use keyboard input').click(); const inputs = host.querySelectorAll('input'); type(window, inputs[0], '2023-02-29'); assert.equal(button(host, 'OK').disabled, true); assert.equal(inputs[0].getAttribute('aria-invalid'), 'true'); type(window, inputs[0], '2024-02-29'); assert.equal(button(host, 'OK').disabled, true); type(window, inputs[1], '2024-03-01'); assert.equal(button(host, 'OK').disabled, false); key(window, inputs[1], 'Enter'); assert.deepEqual(picker.value, { start: '2024-02-29', end: '2024-03-01' });
});
test('date modal supports cancel event without committing draft', t => {
  const { window, host } = fixture(t); window.HTMLDialogElement.prototype.showModal = function() { this.open = true; }; window.HTMLDialogElement.prototype.close = function() { this.open = false; this.dispatchEvent(new window.Event('close')); }; const picker = mountDatePicker(host, { value: '2026-09-19', modal: true }); t.after(() => picker.destroy()); picker.open(); assert.equal(host.querySelector('dialog').open, true); host.querySelector('[data-date="2026-09-22"]').click(); host.querySelector('dialog').dispatchEvent(new window.Event('cancel', { cancelable: true })); assert.equal(picker.value, '2026-09-19'); assert.equal(host.querySelector('dialog').open, false);
});
test('time picker handles midnight/noon, rejects invalid numeric input and cancels draft', t => {
  const { window, host } = fixture(t); const picker = mountTimePicker(host, { value: '00:30', hour24: false }); t.after(() => picker.destroy()); assert.equal(host.querySelector('.qm-time__value').textContent, '12'); button(host, 'PM').click(); button(host, 'OK').click(); assert.equal(picker.value, '12:30'); button(host, 'Use keyboard input').click(); const inputs = host.querySelectorAll('input'); type(window, inputs[0], '13'); assert.equal(button(host, 'OK').disabled, true); type(window, inputs[0], '11'); type(window, inputs[1], '59'); button(host, 'OK').click(); assert.equal(picker.value, '23:59'); type(window, inputs[1], '25'); button(host, 'Cancel').click(); assert.equal(picker.value, '23:59'); assert.equal(inputs[1].value, '59');
});
test('time dial supports keyboard adjustment, 24h wrap and every minute', t => {
  const { window, host } = fixture(t); const picker = mountTimePicker(host, { value: '23:30' }); t.after(() => picker.destroy()); const dial = host.querySelector('[role="slider"]'); key(window, dial, 'ArrowUp'); assert.equal(dial.getAttribute('aria-valuenow'), '0'); key(window, dial, 'Enter'); key(window, dial, 'End'); assert.equal(dial.getAttribute('aria-valuenow'), '59'); key(window, dial, 'ArrowDown'); button(host, 'OK').click(); assert.equal(picker.value, '00:58');
});
test('search renders suggestion text safely and isolates stale asynchronous results', async t => {
  const { window, host } = fixture(t); const resolvers = []; const calls = []; const search = mountSearch(host, { suggestions: ['<img src=x onerror=alert(1)>', 'Material'], onSearch: query => { calls.push(query); return new Promise(resolve => resolvers.push(resolve)); } }); t.after(() => search.destroy()); assert.equal(host.querySelector('img'), null); type(window, search.input, 'first'); host.querySelector('form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); type(window, search.input, 'second'); host.querySelector('form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); resolvers[0](); await Promise.resolve(); assert.equal(host.querySelector('[role="status"]').textContent, 'Searching…'); resolvers[1](); await Promise.resolve(); assert.equal(host.querySelector('[role="status"]').textContent, 'Search complete: second'); assert.deepEqual(calls, ['first', 'second']);
});
test('declarative initialization is idempotent and cleanup removes owned mounts', t => {
  const { doc } = fixture(t, '<div data-qm-date-picker data-value="2026-09-19"></div><div data-qm-time-picker data-value="09:30"></div><div data-qm-search data-suggestions=\'["Material"]\'></div>'); const cleanup = initInputComponents(doc); assert.equal(initInputComponents(doc), cleanup); assert.equal(doc.querySelectorAll('.qm-picker').length, 3); cleanup(); cleanup(); assert.equal(doc.querySelectorAll('.qm-picker').length, 0); const again = initInputComponents(doc); assert.equal(doc.querySelectorAll('.qm-picker').length, 3); again();
});

test('date keyboard traversal clamps at absolute supported year boundaries', t => {
  const { window, doc, host } = fixture(t); const picker = mountDatePicker(host, { value: '9999-12-31' }); t.after(() => picker.destroy()); host.querySelector('[tabindex="0"]').focus(); key(window, doc.activeElement, 'ArrowRight'); assert.equal(doc.activeElement.dataset.date, '9999-12-31'); picker.setValue('0001-01-01'); host.querySelector('[tabindex="0"]').focus(); key(window, doc.activeElement, 'ArrowLeft'); assert.equal(doc.activeElement.dataset.date, '0001-01-01');
});
test('nested menus return focus to parent trigger and outside interaction closes entire tree', t => {
  const { doc, window } = fixture(t, '<button id="trigger" data-qm-menu-trigger="menu">Menu</button><div id="menu" role="menu" hidden><button id="nested" role="menuitem" data-qm-menu-trigger="child">More</button></div><div id="child" role="menu" hidden><button role="menuitem">Child</button></div><button id="outside">Outside</button>'); const cleanup = initInputComponents(doc); t.after(cleanup); doc.querySelector('#trigger').click(); key(window, doc.activeElement, 'ArrowRight'); assert.equal(doc.activeElement.textContent, 'Child'); key(window, doc.activeElement, 'Escape'); assert.equal(doc.activeElement.id, 'nested'); assert.equal(doc.querySelector('#menu').hidden, false); doc.querySelector('#outside').focus(); assert.equal(doc.querySelector('#menu').hidden, true);
});
test('time dial pointer input selects arbitrary minutes and clock face click works', t => {
  const { window, host } = fixture(t); const picker = mountTimePicker(host, { value: '09:30' }); t.after(() => picker.destroy()); host.querySelector('[aria-label="Select minutes"]').click(); const dial = host.querySelector('[role="slider"]'); dial.getBoundingClientRect = () => ({ left: 0, top: 0, width: 280, height: 280 }); const angle = 17 / 60 * 2 * Math.PI; const x = 140 + Math.sin(angle) * 100; const y = 140 - Math.cos(angle) * 100; for (const event of ['pointerdown', 'pointerup']) dial.dispatchEvent(new window.MouseEvent(event, { button: 0, clientX: x, clientY: y, bubbles: true })); button(host, 'OK').click(); assert.equal(picker.value, '09:17'); host.querySelector('[data-clock-value="35"]').click(); button(host, 'OK').click(); assert.equal(picker.value, '09:35');
});

test('search Enter with no suggestion preserves native form submission', t => {
  const { window, host } = fixture(t); const search = mountSearch(host, { suggestions: ['Material'] }); t.after(() => search.destroy()); type(window, search.input, 'No matching suggestion'); const event = key(window, search.input, 'Enter'); assert.equal(event.defaultPrevented, false); assert.equal(search.input.getAttribute('aria-expanded'), 'false');
});
test('disabled comboboxes do not open or commit and disabled fieldset is respected', t => {
  const { window, doc } = fixture(t, '<fieldset disabled><div data-qm-combobox><input role="combobox"><div role="listbox"><div role="option">One</div></div></div></fieldset><div data-qm-combobox><input role="combobox" aria-disabled="true"><div role="listbox"><div role="option">Two</div></div></div>'); const cleanup = initInputComponents(doc); t.after(cleanup); for (const input of doc.querySelectorAll('input')) { input.click(); key(window, input, 'ArrowDown'); assert.equal(input.getAttribute('aria-expanded'), 'false'); } for (const option of doc.querySelectorAll('[role="option"]')) option.click(); for (const input of doc.querySelectorAll('input')) assert.equal(input.value, '');
});
test('empty menu can dismiss from its invoker with Escape', t => {
  const { window, doc } = fixture(t, '<button data-qm-menu-trigger="empty">Empty</button><div role="menu" id="empty" hidden><button role="menuitem" disabled>Unavailable</button></div>'); const cleanup = initInputComponents(doc); t.after(cleanup); const trigger = doc.querySelector('button'); trigger.focus(); trigger.click(); key(window, trigger, 'Escape'); assert.equal(doc.querySelector('#empty').hidden, true); assert.equal(doc.activeElement, trigger);
});
