// Generated from tokens/quiet-material.tokens.json. Run npm run build. Do not edit.
// Dimensions are logical units (CSS px / Android dp or sp / Apple pt / Flutter logical pixels); rem uses a 16-unit baseline. Durations are milliseconds. Apply native text scaling and reduced-motion preferences in components.
package com.quietmaterial

import androidx.compose.ui.graphics.Color

object QuietTokens {
    val colorPaletteBlack: Color = Color(0xFF000000)
    val colorPaletteCharcoal: Color = Color(0xFF242424)
    val colorPaletteCharcoalHigh: Color = Color(0xFF2D2D2D)
    val colorPaletteCharcoalLow: Color = Color(0xFF171717)
    val colorPaletteWhite: Color = Color(0xFFF4F4F4)
    val colorPaletteMuted: Color = Color(0xFFB7B7BD)
    val colorPaletteBlue: Color = Color(0xFFA8C7FA)
    val colorPaletteBlueDark: Color = Color(0xFF10213B)
    val colorPaletteBlueContainer: Color = Color(0xFF24354E)
    val colorPaletteMint: Color = Color(0xFF86D9AE)
    val colorPaletteMintContainer: Color = Color(0xFF153D2B)
    val colorPaletteYellow: Color = Color(0xFFF3D17D)
    val colorPaletteYellowContainer: Color = Color(0xFF423411)
    val colorPaletteRed: Color = Color(0xFFFFB4AB)
    val colorPaletteRedContainer: Color = Color(0xFF522622)
    val colorPaletteOutline: Color = Color(0xFF828289)
    val colorPaletteDisabled: Color = Color(0xFF77777D)
    val colorBackground: Color = Color(0xFF000000)
    val colorSurface: Color = Color(0xFF242424)
    val colorSurfaceHigh: Color = Color(0xFF2D2D2D)
    val colorSurfaceLow: Color = Color(0xFF171717)
    val colorText: Color = Color(0xFFF4F4F4)
    val colorTextMuted: Color = Color(0xFFB7B7BD)
    val colorPrimary: Color = Color(0xFFA8C7FA)
    val colorOnPrimary: Color = Color(0xFF10213B)
    val colorPrimaryContainer: Color = Color(0xFF24354E)
    val colorOnPrimaryContainer: Color = Color(0xFFA8C7FA)
    val colorSecondary: Color = Color(0xFF86D9AE)
    val colorOnSecondary: Color = Color(0xFF153D2B)
    val colorSuccess: Color = Color(0xFF86D9AE)
    val colorSuccessContainer: Color = Color(0xFF153D2B)
    val colorWarning: Color = Color(0xFFF3D17D)
    val colorWarningContainer: Color = Color(0xFF423411)
    val colorDanger: Color = Color(0xFFFFB4AB)
    val colorDangerContainer: Color = Color(0xFF522622)
    val colorOutline: Color = Color(0xFF828289)
    val colorFocus: Color = Color(0xFFA8C7FA)
    val colorDisabled: Color = Color(0xFF77777D)
    val colorAction: Color = Color(0xFFF4F4F4)
    val colorOnAction: Color = Color(0xFF000000)
    const val space0: Float = 0.0f
    const val space1: Float = 4.0f
    const val space2: Float = 8.0f
    const val space3: Float = 12.0f
    const val space4: Float = 16.0f
    const val space5: Float = 20.0f
    const val space6: Float = 24.0f
    const val space7: Float = 28.0f
    const val space8: Float = 32.0f
    const val space9: Float = 36.0f
    const val space10: Float = 40.0f
    const val space11: Float = 44.0f
    const val space12: Float = 48.0f
    const val radiusSmall: Float = 8.0f
    const val radiusControl: Float = 16.0f
    const val radiusCard: Float = 40.0f
    const val radiusDialog: Float = 32.0f
    const val radiusPill: Float = 999.0f
    const val radiusCardCompact: Float = 32.0f
    val fontBody: List<String> = listOf("Inter", "Roboto", "Arial", "sans-serif")
    val fontMono: List<String> = listOf("ui-monospace", "SFMono-Regular", "Consolas", "monospace")
    const val fontRegular: Int = 400
    const val fontMedium: Int = 500
    const val fontBold: Int = 600
    const val typeDisplay: Float = 56.0f
    const val typeHeadline: Float = 36.0f
    const val typeTitle: Float = 24.0f
    const val typeBody: Float = 16.0f
    const val typeLabel: Float = 14.0f
    const val typeCaption: Float = 12.0f
    const val lineHeightTight: Float = 1.1f
    const val lineHeightHeading: Float = 1.25f
    const val lineHeightBody: Float = 1.6f
    const val lineHeightControl: Float = 1.25f
    const val durationInstant: Int = 100
    const val durationShort: Int = 150
    const val durationMedium: Int = 250
    const val durationLong: Int = 350
    val easingStandard: FloatArray = floatArrayOf(0.2f, 0.0f, 0.0f, 1.0f)
    val easingEnter: FloatArray = floatArrayOf(0.0f, 0.0f, 0.0f, 1.0f)
    val easingExit: FloatArray = floatArrayOf(0.3f, 0.0f, 1.0f, 1.0f)
    const val sizeControl: Float = 48.0f
    const val sizeContent: Float = 1200.0f
    const val sizeReading: Float = 720.0f
    const val sizeSidebar: Float = 256.0f
    const val sizeTouchTarget: Float = 48.0f
    const val borderWidth: Float = 1.0f
    const val borderFocus: Float = 3.0f
    const val breakpointMedium: Float = 600.0f
    const val breakpointExpanded: Float = 840.0f
    const val breakpointWide: Float = 1200.0f
    const val layoutPagePaddingCompact: Float = 20.0f
    const val layoutPagePaddingMedium: Float = 32.0f
    const val layoutPagePaddingExpanded: Float = 48.0f
}
