// Generated from tokens/quiet-material.tokens.json. Run npm run build. Do not edit.
// Dimensions are logical units (CSS px / Android dp or sp / Apple pt / Flutter logical pixels); rem uses a 16-unit baseline. Durations are milliseconds. Apply native text scaling and reduced-motion preferences in components.
package com.quietmaterial

import androidx.compose.ui.graphics.Color

object QuietTokens {
    val colorPaletteBlack: Color = Color(0xFF000000)
    val colorPaletteCharcoal: Color = Color(0xFF101010)
    val colorPaletteCharcoalHigh: Color = Color(0xFF181818)
    val colorPaletteGraphite: Color = Color(0xFF242424)
    val colorPaletteCharcoalLow: Color = Color(0xFF080808)
    val colorPaletteWhite: Color = Color(0xFFF4F4F4)
    val colorPaletteMuted: Color = Color(0xFFB7B7B7)
    val colorPaletteBlue: Color = Color(0xFFA8C7FA)
    val colorPaletteBlueDark: Color = Color(0xFF10213B)
    val colorPaletteBlueContainer: Color = Color(0xFF24354E)
    val colorPaletteMint: Color = Color(0xFF86D9AE)
    val colorPaletteMintContainer: Color = Color(0xFF153D2B)
    val colorPaletteYellow: Color = Color(0xFFF3D17D)
    val colorPaletteYellowContainer: Color = Color(0xFF423411)
    val colorPaletteRed: Color = Color(0xFFFFB4AB)
    val colorPaletteRedContainer: Color = Color(0xFF522622)
    val colorPaletteOutline: Color = Color(0xFF828282)
    val colorPaletteDisabled: Color = Color(0xFF777777)
    val colorPaletteShadowSoft: Color = Color(0x99000000)
    val colorPaletteShadowStrong: Color = Color(0xCC000000)
    val colorPaletteScrim: Color = Color(0xCC000000)
    val colorBackground: Color = Color(0xFF000000)
    val colorSurface: Color = Color(0xFF101010)
    val colorSurfaceHigh: Color = Color(0xFF181818)
    val colorSurfaceLow: Color = Color(0xFF080808)
    val colorText: Color = Color(0xFFF4F4F4)
    val colorTextMuted: Color = Color(0xFFB7B7B7)
    val colorPrimary: Color = Color(0xFFF4F4F4)
    val colorOnPrimary: Color = Color(0xFF000000)
    val colorPrimaryContainer: Color = Color(0xFF242424)
    val colorOnPrimaryContainer: Color = Color(0xFFF4F4F4)
    val colorSecondary: Color = Color(0xFFB7B7B7)
    val colorOnSecondary: Color = Color(0xFF000000)
    val colorSuccess: Color = Color(0xFF86D9AE)
    val colorSuccessContainer: Color = Color(0xFF153D2B)
    val colorWarning: Color = Color(0xFFF3D17D)
    val colorWarningContainer: Color = Color(0xFF423411)
    val colorDanger: Color = Color(0xFFFFB4AB)
    val colorDangerContainer: Color = Color(0xFF522622)
    val colorOutline: Color = Color(0xFF828282)
    val colorOutlineVariant: Color = Color(0xFF242424)
    val colorFocus: Color = Color(0xFFF4F4F4)
    val colorFocusContrast: Color = Color(0xFF000000)
    val colorDisabled: Color = Color(0xFF777777)
    val colorAction: Color = Color(0xFFF4F4F4)
    val colorOnAction: Color = Color(0xFF000000)
    val colorScrim: Color = Color(0xCC000000)
    const val space0: Float = 0.0f
    const val space1: Float = 4.0f
    const val space2: Float = 8.0f
    const val space3: Float = 12.0f
    const val space4: Float = 16.0f
    const val space5: Float = 20.0f
    const val space6: Float = 24.0f
    const val space7: Float = 28.0f
    const val space8: Float = 32.0f
    const val space9: Float = 36.0f
    const val space10: Float = 40.0f
    const val space11: Float = 44.0f
    const val space12: Float = 48.0f
    const val radiusSmall: Float = 8.0f
    const val radiusTile: Float = 12.0f
    const val radiusControl: Float = 16.0f
    const val radiusCard: Float = 24.0f
    const val radiusFeature: Float = 32.0f
    const val radiusDialog: Float = 32.0f
    const val radiusPill: Float = 999.0f
    const val radiusCardCompact: Float = 24.0f
    val fontBody: List<String> = listOf("Inter", "Roboto", "Arial", "sans-serif")
    val fontMono: List<String> = listOf("ui-monospace", "SFMono-Regular", "Consolas", "monospace")
    const val fontRegular: Int = 400
    const val fontMedium: Int = 500
    const val fontBold: Int = 600
    const val typeDisplay: Float = 56.0f
    const val typeHeadline: Float = 36.0f
    const val typeTitle: Float = 24.0f
    const val typeBody: Float = 16.0f
    const val typeLabel: Float = 14.0f
    const val typeCaption: Float = 12.0f
    const val lineHeightTight: Float = 1.1f
    const val lineHeightHeading: Float = 1.25f
    const val lineHeightBody: Float = 1.6f
    const val lineHeightControl: Float = 1.25f
    const val durationShort1: Int = 50
    const val durationShort2: Int = 100
    const val durationShort3: Int = 150
    const val durationShort4: Int = 200
    const val durationMedium1: Int = 250
    const val durationMedium2: Int = 300
    const val durationMedium3: Int = 350
    const val durationMedium4: Int = 400
    const val durationLong1: Int = 450
    const val durationLong2: Int = 500
    const val durationLong3: Int = 550
    const val durationLong4: Int = 600
    const val durationExtraLong1: Int = 700
    const val durationExtraLong2: Int = 800
    const val durationExtraLong3: Int = 900
    const val durationExtraLong4: Int = 1000
    const val durationInstant: Int = 100
    const val durationShort: Int = 150
    const val durationMedium: Int = 250
    const val durationLong: Int = 350
    val easingStandard: FloatArray = floatArrayOf(0.2f, 0.0f, 0.0f, 1.0f)
    val easingStandardAccelerate: FloatArray = floatArrayOf(0.3f, 0.0f, 1.0f, 1.0f)
    val easingStandardDecelerate: FloatArray = floatArrayOf(0.0f, 0.0f, 0.0f, 1.0f)
    val easingEmphasizedFirst: FloatArray = floatArrayOf(0.3000012000048f, 0.0f, 0.8000012000048f, 0.15f)
    val easingEmphasizedSecond: FloatArray = floatArrayOf(0.050000359999711974f, 0.7f, 0.10000071999942399f, 1.0f)
    const val easingEmphasizedJoinX: Float = 0.166666f
    const val easingEmphasizedJoinY: Float = 0.4f
    val easingEmphasizedAccelerate: FloatArray = floatArrayOf(0.3f, 0.0f, 0.8f, 0.15f)
    val easingEmphasizedDecelerate: FloatArray = floatArrayOf(0.05f, 0.7f, 0.1f, 1.0f)
    val easingLinear: FloatArray = floatArrayOf(0.0f, 0.0f, 1.0f, 1.0f)
    val easingLegacy: FloatArray = floatArrayOf(0.4f, 0.0f, 0.2f, 1.0f)
    val easingLegacyAccelerate: FloatArray = floatArrayOf(0.4f, 0.0f, 1.0f, 1.0f)
    val easingLegacyDecelerate: FloatArray = floatArrayOf(0.0f, 0.0f, 0.2f, 1.0f)
    val easingEnter: FloatArray = floatArrayOf(0.0f, 0.0f, 0.0f, 1.0f)
    val easingExit: FloatArray = floatArrayOf(0.3f, 0.0f, 1.0f, 1.0f)
    const val sizeControl: Float = 48.0f
    const val sizeContent: Float = 1200.0f
    const val sizeReading: Float = 720.0f
    const val sizeSidebar: Float = 256.0f
    const val sizeTouchTarget: Float = 48.0f
    const val borderWidth: Float = 1.0f
    const val borderFocus: Float = 3.0f
    const val borderFocusOffset: Float = 2.0f
    const val breakpointMedium: Float = 600.0f
    const val breakpointExpanded: Float = 840.0f
    const val breakpointWide: Float = 1200.0f
    const val layoutPagePaddingCompact: Float = 20.0f
    const val layoutPagePaddingMedium: Float = 32.0f
    const val layoutPagePaddingExpanded: Float = 48.0f
    const val springStandardFastSpatialDamping: Float = 0.9f
    const val springStandardFastSpatialStiffness: Float = 1400.0f
    const val springStandardFastEffectsDamping: Float = 1.0f
    const val springStandardFastEffectsStiffness: Float = 3800.0f
    const val springStandardDefaultSpatialDamping: Float = 0.9f
    const val springStandardDefaultSpatialStiffness: Float = 700.0f
    const val springStandardDefaultEffectsDamping: Float = 1.0f
    const val springStandardDefaultEffectsStiffness: Float = 1600.0f
    const val springStandardSlowSpatialDamping: Float = 0.9f
    const val springStandardSlowSpatialStiffness: Float = 300.0f
    const val springStandardSlowEffectsDamping: Float = 1.0f
    const val springStandardSlowEffectsStiffness: Float = 800.0f
    const val springExpressiveFastSpatialDamping: Float = 0.6f
    const val springExpressiveFastSpatialStiffness: Float = 800.0f
    const val springExpressiveFastEffectsDamping: Float = 1.0f
    const val springExpressiveFastEffectsStiffness: Float = 3800.0f
    const val springExpressiveDefaultSpatialDamping: Float = 0.8f
    const val springExpressiveDefaultSpatialStiffness: Float = 380.0f
    const val springExpressiveDefaultEffectsDamping: Float = 1.0f
    const val springExpressiveDefaultEffectsStiffness: Float = 1600.0f
    const val springExpressiveSlowSpatialDamping: Float = 0.8f
    const val springExpressiveSlowSpatialStiffness: Float = 200.0f
    const val springExpressiveSlowEffectsDamping: Float = 1.0f
    const val springExpressiveSlowEffectsStiffness: Float = 800.0f
    const val motionStateDuration: Int = 150
    val motionStateEasing: FloatArray = floatArrayOf(0.2f, 0.0f, 0.0f, 1.0f)
    const val motionControlDuration: Int = 300
    val motionControlEasing: FloatArray = floatArrayOf(0.2f, 0.0f, 0.0f, 1.0f)
    const val motionEnterDuration: Int = 500
    val motionEnterEasing: FloatArray = floatArrayOf(0.05f, 0.7f, 0.1f, 1.0f)
    const val motionExitDuration: Int = 200
    val motionExitEasing: FloatArray = floatArrayOf(0.3f, 0.0f, 0.8f, 0.15f)
    const val motionContainerDuration: Int = 500
    const val motionSharedAxisDuration: Int = 450
    const val motionFadeThroughDuration: Int = 450
    const val motionFadeEnterDuration: Int = 400
    val motionFadeEnterEasing: FloatArray = floatArrayOf(0.05f, 0.7f, 0.1f, 1.0f)
    const val motionFadeExitDuration: Int = 150
    val motionFadeExitEasing: FloatArray = floatArrayOf(0.3f, 0.0f, 0.8f, 0.15f)
    const val motionRippleGrowDuration: Int = 450
    const val motionRippleMinimumPressDuration: Int = 225
    const val motionRippleTouchDelay: Int = 150
    const val motionRippleFadeInDuration: Int = 105
    const val motionRippleFadeDuration: Int = 375
    const val motionRippleHoverDuration: Int = 15
    val motionRippleEasing: FloatArray = floatArrayOf(0.2f, 0.0f, 0.0f, 1.0f)
    const val motionContainerReturnDuration: Int = 400
    const val elevationLevel1OffsetY: Float = 1.0f
    const val elevationLevel1Blur: Float = 2.0f
    val elevationLevel1Color: Color = Color(0x99000000)
    const val elevationLevel2OffsetY: Float = 2.0f
    const val elevationLevel2Blur: Float = 8.0f
    val elevationLevel2Color: Color = Color(0x99000000)
    const val elevationLevel3OffsetY: Float = 8.0f
    const val elevationLevel3Blur: Float = 24.0f
    val elevationLevel3Color: Color = Color(0xCC000000)
    const val layerBase: Float = 0.0f
    const val layerRaised: Float = 1.0f
    const val layerSticky: Float = 10.0f
    const val layerFloating: Float = 20.0f
    const val layerOverlay: Float = 30.0f
    const val layerPopover: Float = 40.0f
    const val stateHover: Float = 0.08f
    const val stateFocus: Float = 0.12f
    const val statePressed: Float = 0.12f
    const val stateDragged: Float = 0.16f
}
