// Generated from tokens/quiet-material.tokens.json. Run npm run build. Do not edit.
// Dimensions are logical units (CSS px / Android dp or sp / Apple pt / Flutter logical pixels); rem uses a 16-unit baseline. Durations are milliseconds. Apply native text scaling and reduced-motion preferences in components.
export const quietTokens = {
  "colorPaletteBlack": "#000000",
  "colorPaletteCharcoal": "#242424",
  "colorPaletteCharcoalHigh": "#2d2d2d",
  "colorPaletteCharcoalLow": "#171717",
  "colorPaletteWhite": "#f4f4f4",
  "colorPaletteMuted": "#b7b7bd",
  "colorPaletteBlue": "#a8c7fa",
  "colorPaletteBlueDark": "#10213b",
  "colorPaletteBlueContainer": "#24354e",
  "colorPaletteMint": "#86d9ae",
  "colorPaletteMintContainer": "#153d2b",
  "colorPaletteYellow": "#f3d17d",
  "colorPaletteYellowContainer": "#423411",
  "colorPaletteRed": "#ffb4ab",
  "colorPaletteRedContainer": "#522622",
  "colorPaletteOutline": "#828289",
  "colorPaletteDisabled": "#77777d",
  "colorBackground": "#000000",
  "colorSurface": "#242424",
  "colorSurfaceHigh": "#2d2d2d",
  "colorSurfaceLow": "#171717",
  "colorText": "#f4f4f4",
  "colorTextMuted": "#b7b7bd",
  "colorPrimary": "#a8c7fa",
  "colorOnPrimary": "#10213b",
  "colorPrimaryContainer": "#24354e",
  "colorOnPrimaryContainer": "#a8c7fa",
  "colorSecondary": "#86d9ae",
  "colorOnSecondary": "#153d2b",
  "colorSuccess": "#86d9ae",
  "colorSuccessContainer": "#153d2b",
  "colorWarning": "#f3d17d",
  "colorWarningContainer": "#423411",
  "colorDanger": "#ffb4ab",
  "colorDangerContainer": "#522622",
  "colorOutline": "#828289",
  "colorFocus": "#a8c7fa",
  "colorDisabled": "#77777d",
  "colorAction": "#f4f4f4",
  "colorOnAction": "#000000",
  "space0": 0,
  "space1": 4,
  "space2": 8,
  "space3": 12,
  "space4": 16,
  "space5": 20,
  "space6": 24,
  "space7": 28,
  "space8": 32,
  "space9": 36,
  "space10": 40,
  "space11": 44,
  "space12": 48,
  "radiusSmall": 8,
  "radiusControl": 16,
  "radiusCard": 40,
  "radiusDialog": 32,
  "radiusPill": 999,
  "radiusCardCompact": 32,
  "fontBody": [
    "Inter",
    "Roboto",
    "Arial",
    "sans-serif"
  ],
  "fontMono": [
    "ui-monospace",
    "SFMono-Regular",
    "Consolas",
    "monospace"
  ],
  "fontRegular": 400,
  "fontMedium": 500,
  "fontBold": 600,
  "typeDisplay": 56,
  "typeHeadline": 36,
  "typeTitle": 24,
  "typeBody": 16,
  "typeLabel": 14,
  "typeCaption": 12,
  "lineHeightTight": 1.1,
  "lineHeightHeading": 1.25,
  "lineHeightBody": 1.6,
  "lineHeightControl": 1.25,
  "durationInstant": 100,
  "durationShort": 150,
  "durationMedium": 250,
  "durationLong": 350,
  "easingStandard": [
    0.2,
    0,
    0,
    1
  ],
  "easingEnter": [
    0,
    0,
    0,
    1
  ],
  "easingExit": [
    0.3,
    0,
    1,
    1
  ],
  "sizeControl": 48,
  "sizeContent": 1200,
  "sizeReading": 720,
  "sizeSidebar": 256,
  "sizeTouchTarget": 48,
  "borderWidth": 1,
  "borderFocus": 3,
  "breakpointMedium": 600,
  "breakpointExpanded": 840,
  "breakpointWide": 1200,
  "layoutPagePaddingCompact": 20,
  "layoutPagePaddingMedium": 32,
  "layoutPagePaddingExpanded": 48
} as const;

export type QuietTokenName = keyof typeof quietTokens;
export type QuietTokens = typeof quietTokens;
